### ISSUE TITLE
Audio is slience on iOS devices and Safari browser (using touchpad) when sound model is initialized on first load

### ISSUE THREAD

**Issue by hongkheng** [Sonoport/soundmodels#6]
`window.audioContext.currentTime` still remains `0` even if the `touchend` event is detected.

Apparently the fix is to connect the dummy `bootOsc` to destination and disconnect again (to remove it) to enable `window.audioContext.currentTime` to start running on first user touch.

**Comment by hongkheng** [comment]
7d85c1bc97b736cfe0a426d9e0c52ccbe0e32e97 fix this issue

**Comment by notthetup** [comment]
:+1:
